/*
 * Flickr API Schema
 * A subset of Flickr's API defined in Swagger format.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.GroupDescription;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for PersonPhotos
 */
public class PersonPhotosTest {
    private final PersonPhotos model = new PersonPhotos();

    /**
     * Model tests for PersonPhotos
     */
    @Test
    public void testPersonPhotos() {
        // TODO: test PersonPhotos
    }

    /**
     * Test the property 'count'
     */
    @Test
    public void countTest() {
        // TODO: test count
    }

    /**
     * Test the property 'firstdate'
     */
    @Test
    public void firstdateTest() {
        // TODO: test firstdate
    }

    /**
     * Test the property 'firstdatetaken'
     */
    @Test
    public void firstdatetakenTest() {
        // TODO: test firstdatetaken
    }

    /**
     * Test the property 'views'
     */
    @Test
    public void viewsTest() {
        // TODO: test views
    }

}
