/*
 * Flickr API Schema
 * A subset of Flickr's API defined in Swagger format.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.GroupDescription;
import com.konfigthis.client.model.Owner;
import com.konfigthis.client.model.PhotoDates;
import com.konfigthis.client.model.PhotoEditability;
import com.konfigthis.client.model.PhotoNotes;
import com.konfigthis.client.model.PhotoPeople;
import com.konfigthis.client.model.PhotoPermissions;
import com.konfigthis.client.model.PhotoTags;
import com.konfigthis.client.model.PhotoUrls;
import com.konfigthis.client.model.PhotoUsage;
import com.konfigthis.client.model.PhotoVisibility;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for Photo
 */
public class PhotoTest {
    private final Photo model = new Photo();

    /**
     * Model tests for Photo
     */
    @Test
    public void testPhoto() {
        // TODO: test Photo
    }

    /**
     * Test the property 'tags'
     */
    @Test
    public void tagsTest() {
        // TODO: test tags
    }

    /**
     * Test the property 'title'
     */
    @Test
    public void titleTest() {
        // TODO: test title
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'comments'
     */
    @Test
    public void commentsTest() {
        // TODO: test comments
    }

    /**
     * Test the property 'dates'
     */
    @Test
    public void datesTest() {
        // TODO: test dates
    }

    /**
     * Test the property 'dateuploaded'
     */
    @Test
    public void dateuploadedTest() {
        // TODO: test dateuploaded
    }

    /**
     * Test the property 'editability'
     */
    @Test
    public void editabilityTest() {
        // TODO: test editability
    }

    /**
     * Test the property 'farm'
     */
    @Test
    public void farmTest() {
        // TODO: test farm
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'isfavorite'
     */
    @Test
    public void isfavoriteTest() {
        // TODO: test isfavorite
    }

    /**
     * Test the property 'license'
     */
    @Test
    public void licenseTest() {
        // TODO: test license
    }

    /**
     * Test the property 'media'
     */
    @Test
    public void mediaTest() {
        // TODO: test media
    }

    /**
     * Test the property 'notes'
     */
    @Test
    public void notesTest() {
        // TODO: test notes
    }

    /**
     * Test the property 'originalsecret'
     */
    @Test
    public void originalsecretTest() {
        // TODO: test originalsecret
    }

    /**
     * Test the property 'owner'
     */
    @Test
    public void ownerTest() {
        // TODO: test owner
    }

    /**
     * Test the property 'people'
     */
    @Test
    public void peopleTest() {
        // TODO: test people
    }

    /**
     * Test the property 'permissions'
     */
    @Test
    public void permissionsTest() {
        // TODO: test permissions
    }

    /**
     * Test the property 'publiceditability'
     */
    @Test
    public void publiceditabilityTest() {
        // TODO: test publiceditability
    }

    /**
     * Test the property 'rotation'
     */
    @Test
    public void rotationTest() {
        // TODO: test rotation
    }

    /**
     * Test the property 'safe'
     */
    @Test
    public void safeTest() {
        // TODO: test safe
    }

    /**
     * Test the property 'safetyLevel'
     */
    @Test
    public void safetyLevelTest() {
        // TODO: test safetyLevel
    }

    /**
     * Test the property 'secret'
     */
    @Test
    public void secretTest() {
        // TODO: test secret
    }

    /**
     * Test the property 'server'
     */
    @Test
    public void serverTest() {
        // TODO: test server
    }

    /**
     * Test the property 'urls'
     */
    @Test
    public void urlsTest() {
        // TODO: test urls
    }

    /**
     * Test the property 'usage'
     */
    @Test
    public void usageTest() {
        // TODO: test usage
    }

    /**
     * Test the property 'views'
     */
    @Test
    public void viewsTest() {
        // TODO: test views
    }

    /**
     * Test the property 'visibility'
     */
    @Test
    public void visibilityTest() {
        // TODO: test visibility
    }

}
