/*
 * Flickr API Schema
 * A subset of Flickr's API defined in Swagger format.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for PhotoPermissions
 */
public class PhotoPermissionsTest {
    private final PhotoPermissions model = new PhotoPermissions();

    /**
     * Model tests for PhotoPermissions
     */
    @Test
    public void testPhotoPermissions() {
        // TODO: test PhotoPermissions
    }

    /**
     * Test the property 'permaddmeta'
     */
    @Test
    public void permaddmetaTest() {
        // TODO: test permaddmeta
    }

    /**
     * Test the property 'permcomment'
     */
    @Test
    public void permcommentTest() {
        // TODO: test permcomment
    }

}
