/*
 * Flickr API Schema
 * A subset of Flickr's API defined in Swagger format.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for PhotoVisibility
 */
public class PhotoVisibilityTest {
    private final PhotoVisibility model = new PhotoVisibility();

    /**
     * Model tests for PhotoVisibility
     */
    @Test
    public void testPhotoVisibility() {
        // TODO: test PhotoVisibility
    }

    /**
     * Test the property 'isfamily'
     */
    @Test
    public void isfamilyTest() {
        // TODO: test isfamily
    }

    /**
     * Test the property 'isfriend'
     */
    @Test
    public void isfriendTest() {
        // TODO: test isfriend
    }

    /**
     * Test the property 'ispublic'
     */
    @Test
    public void ispublicTest() {
        // TODO: test ispublic
    }

}
