/*
 * Flickr API Schema
 * A subset of Flickr's API defined in Swagger format.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.File;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for PublicUploadPhotoRequest
 */
public class PublicUploadPhotoRequestTest {
    private final PublicUploadPhotoRequest model = new PublicUploadPhotoRequest();

    /**
     * Model tests for PublicUploadPhotoRequest
     */
    @Test
    public void testPublicUploadPhotoRequest() {
        // TODO: test PublicUploadPhotoRequest
    }

    /**
     * Test the property 'tags'
     */
    @Test
    public void tagsTest() {
        // TODO: test tags
    }

    /**
     * Test the property 'title'
     */
    @Test
    public void titleTest() {
        // TODO: test title
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'apiKey'
     */
    @Test
    public void apiKeyTest() {
        // TODO: test apiKey
    }

    /**
     * Test the property 'contentType'
     */
    @Test
    public void contentTypeTest() {
        // TODO: test contentType
    }

    /**
     * Test the property 'hidden'
     */
    @Test
    public void hiddenTest() {
        // TODO: test hidden
    }

    /**
     * Test the property 'isFamily'
     */
    @Test
    public void isFamilyTest() {
        // TODO: test isFamily
    }

    /**
     * Test the property 'isFriend'
     */
    @Test
    public void isFriendTest() {
        // TODO: test isFriend
    }

    /**
     * Test the property 'isPublic'
     */
    @Test
    public void isPublicTest() {
        // TODO: test isPublic
    }

    /**
     * Test the property 'photo'
     */
    @Test
    public void photoTest() {
        // TODO: test photo
    }

    /**
     * Test the property 'safetyLevel'
     */
    @Test
    public void safetyLevelTest() {
        // TODO: test safetyLevel
    }

}
