/*
 * Flickr API Schema
 * A subset of Flickr's API defined in Swagger format.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.PublicGetPhotoExifResponsePhotoExifInner;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for PublicGetPhotoExifResponsePhoto
 */
public class PublicGetPhotoExifResponsePhotoTest {
    private final PublicGetPhotoExifResponsePhoto model = new PublicGetPhotoExifResponsePhoto();

    /**
     * Model tests for PublicGetPhotoExifResponsePhoto
     */
    @Test
    public void testPublicGetPhotoExifResponsePhoto() {
        // TODO: test PublicGetPhotoExifResponsePhoto
    }

    /**
     * Test the property 'camera'
     */
    @Test
    public void cameraTest() {
        // TODO: test camera
    }

    /**
     * Test the property 'exif'
     */
    @Test
    public void exifTest() {
        // TODO: test exif
    }

    /**
     * Test the property 'farm'
     */
    @Test
    public void farmTest() {
        // TODO: test farm
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'secret'
     */
    @Test
    public void secretTest() {
        // TODO: test secret
    }

    /**
     * Test the property 'server'
     */
    @Test
    public void serverTest() {
        // TODO: test server
    }

}
