/*
 * Flickr API Schema
 * A subset of Flickr's API defined in Swagger format.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.PublicGetPhotoLicensesResponseLicenses;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for PublicGetPhotoLicensesResponse
 */
public class PublicGetPhotoLicensesResponseTest {
    private final PublicGetPhotoLicensesResponse model = new PublicGetPhotoLicensesResponse();

    /**
     * Model tests for PublicGetPhotoLicensesResponse
     */
    @Test
    public void testPublicGetPhotoLicensesResponse() {
        // TODO: test PublicGetPhotoLicensesResponse
    }

    /**
     * Test the property 'licenses'
     */
    @Test
    public void licensesTest() {
        // TODO: test licenses
    }

    /**
     * Test the property 'stat'
     */
    @Test
    public void statTest() {
        // TODO: test stat
    }

}
