/*
 * Flickr API Schema
 * A subset of Flickr's API defined in Swagger format.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.Album;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for PublicGetUserAlbumsResponse
 */
public class PublicGetUserAlbumsResponseTest {
    private final PublicGetUserAlbumsResponse model = new PublicGetUserAlbumsResponse();

    /**
     * Model tests for PublicGetUserAlbumsResponse
     */
    @Test
    public void testPublicGetUserAlbumsResponse() {
        // TODO: test PublicGetUserAlbumsResponse
    }

    /**
     * Test the property 'page'
     */
    @Test
    public void pageTest() {
        // TODO: test page
    }

    /**
     * Test the property 'pages'
     */
    @Test
    public void pagesTest() {
        // TODO: test pages
    }

    /**
     * Test the property 'perpage'
     */
    @Test
    public void perpageTest() {
        // TODO: test perpage
    }

    /**
     * Test the property 'photosets'
     */
    @Test
    public void photosetsTest() {
        // TODO: test photosets
    }

    /**
     * Test the property 'total'
     */
    @Test
    public void totalTest() {
        // TODO: test total
    }

}
