/*
 * Flickr API Schema
 * A subset of Flickr's API defined in Swagger format.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.Size;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for PublicGetPhotoSizesResponseSizes
 */
public class PublicGetPhotoSizesResponseSizesTest {
    private final PublicGetPhotoSizesResponseSizes model = new PublicGetPhotoSizesResponseSizes();

    /**
     * Model tests for PublicGetPhotoSizesResponseSizes
     */
    @Test
    public void testPublicGetPhotoSizesResponseSizes() {
        // TODO: test PublicGetPhotoSizesResponseSizes
    }

    /**
     * Test the property 'canblog'
     */
    @Test
    public void canblogTest() {
        // TODO: test canblog
    }

    /**
     * Test the property 'candownload'
     */
    @Test
    public void candownloadTest() {
        // TODO: test candownload
    }

    /**
     * Test the property 'canprint'
     */
    @Test
    public void canprintTest() {
        // TODO: test canprint
    }

    /**
     * Test the property 'sizes'
     */
    @Test
    public void sizesTest() {
        // TODO: test sizes
    }

}
