/*
 * Flickr API Schema
 * A subset of Flickr's API defined in Swagger format.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.GroupDescription;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for PublicGetFlickrTestEchoResponse
 */
public class PublicGetFlickrTestEchoResponseTest {
    private final PublicGetFlickrTestEchoResponse model = new PublicGetFlickrTestEchoResponse();

    /**
     * Model tests for PublicGetFlickrTestEchoResponse
     */
    @Test
    public void testPublicGetFlickrTestEchoResponse() {
        // TODO: test PublicGetFlickrTestEchoResponse
    }

    /**
     * Test the property 'echo'
     */
    @Test
    public void echoTest() {
        // TODO: test echo
    }

}
