/*
 * Flickr API Schema
 * A subset of Flickr's API defined in Swagger format.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.Topic;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for PublicGetGroupTopicInfoResponse
 */
public class PublicGetGroupTopicInfoResponseTest {
    private final PublicGetGroupTopicInfoResponse model = new PublicGetGroupTopicInfoResponse();

    /**
     * Model tests for PublicGetGroupTopicInfoResponse
     */
    @Test
    public void testPublicGetGroupTopicInfoResponse() {
        // TODO: test PublicGetGroupTopicInfoResponse
    }

    /**
     * Test the property 'stat'
     */
    @Test
    public void statTest() {
        // TODO: test stat
    }

    /**
     * Test the property 'topic'
     */
    @Test
    public void topicTest() {
        // TODO: test topic
    }

}
