/*
 * Flickr API Schema
 * A subset of Flickr's API defined in Swagger format.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.Topic;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for PublicGetGroupDiscussionTopicsResponse
 */
public class PublicGetGroupDiscussionTopicsResponseTest {
    private final PublicGetGroupDiscussionTopicsResponse model = new PublicGetGroupDiscussionTopicsResponse();

    /**
     * Model tests for PublicGetGroupDiscussionTopicsResponse
     */
    @Test
    public void testPublicGetGroupDiscussionTopicsResponse() {
        // TODO: test PublicGetGroupDiscussionTopicsResponse
    }

    /**
     * Test the property 'iconfarm'
     */
    @Test
    public void iconfarmTest() {
        // TODO: test iconfarm
    }

    /**
     * Test the property 'iconserver'
     */
    @Test
    public void iconserverTest() {
        // TODO: test iconserver
    }

    /**
     * Test the property 'ispoolmoderated'
     */
    @Test
    public void ispoolmoderatedTest() {
        // TODO: test ispoolmoderated
    }

    /**
     * Test the property 'lang'
     */
    @Test
    public void langTest() {
        // TODO: test lang
    }

    /**
     * Test the property 'members'
     */
    @Test
    public void membersTest() {
        // TODO: test members
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'page'
     */
    @Test
    public void pageTest() {
        // TODO: test page
    }

    /**
     * Test the property 'pages'
     */
    @Test
    public void pagesTest() {
        // TODO: test pages
    }

    /**
     * Test the property 'perPage'
     */
    @Test
    public void perPageTest() {
        // TODO: test perPage
    }

    /**
     * Test the property 'privacy'
     */
    @Test
    public void privacyTest() {
        // TODO: test privacy
    }

    /**
     * Test the property 'topics'
     */
    @Test
    public void topicsTest() {
        // TODO: test topics
    }

    /**
     * Test the property 'total'
     */
    @Test
    public void totalTest() {
        // TODO: test total
    }

}
