/*
 * Flickr API Schema
 * A subset of Flickr's API defined in Swagger format.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.GroupDescription;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for PublicGetPhotoExifResponsePhotoExifInner
 */
public class PublicGetPhotoExifResponsePhotoExifInnerTest {
    private final PublicGetPhotoExifResponsePhotoExifInner model = new PublicGetPhotoExifResponsePhotoExifInner();

    /**
     * Model tests for PublicGetPhotoExifResponsePhotoExifInner
     */
    @Test
    public void testPublicGetPhotoExifResponsePhotoExifInner() {
        // TODO: test PublicGetPhotoExifResponsePhotoExifInner
    }

    /**
     * Test the property 'label'
     */
    @Test
    public void labelTest() {
        // TODO: test label
    }

    /**
     * Test the property 'raw'
     */
    @Test
    public void rawTest() {
        // TODO: test raw
    }

    /**
     * Test the property 'tag'
     */
    @Test
    public void tagTest() {
        // TODO: test tag
    }

    /**
     * Test the property 'tagspace'
     */
    @Test
    public void tagspaceTest() {
        // TODO: test tagspace
    }

    /**
     * Test the property 'tagspaceid'
     */
    @Test
    public void tagspaceidTest() {
        // TODO: test tagspaceid
    }

}
