/*
 * Flickr API Schema
 * A subset of Flickr's API defined in Swagger format.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.ContextPhoto;
import com.konfigthis.client.model.GroupDescription;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for PublicFlickrGroupsPoolsGetContextResponse
 */
public class PublicFlickrGroupsPoolsGetContextResponseTest {
    private final PublicFlickrGroupsPoolsGetContextResponse model = new PublicFlickrGroupsPoolsGetContextResponse();

    /**
     * Model tests for PublicFlickrGroupsPoolsGetContextResponse
     */
    @Test
    public void testPublicFlickrGroupsPoolsGetContextResponse() {
        // TODO: test PublicFlickrGroupsPoolsGetContextResponse
    }

    /**
     * Test the property 'count'
     */
    @Test
    public void countTest() {
        // TODO: test count
    }

    /**
     * Test the property 'nextphoto'
     */
    @Test
    public void nextphotoTest() {
        // TODO: test nextphoto
    }

    /**
     * Test the property 'prevphoto'
     */
    @Test
    public void prevphotoTest() {
        // TODO: test prevphoto
    }

    /**
     * Test the property 'stat'
     */
    @Test
    public void statTest() {
        // TODO: test stat
    }

}
