/*
 * Flickr API Schema
 * A subset of Flickr's API defined in Swagger format.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.GroupDescription;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * PersonPhotos
 */@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class PersonPhotos {
  public static final String SERIALIZED_NAME_COUNT = "count";
  @SerializedName(SERIALIZED_NAME_COUNT)
  private GroupDescription count;

  public static final String SERIALIZED_NAME_FIRSTDATE = "firstdate";
  @SerializedName(SERIALIZED_NAME_FIRSTDATE)
  private GroupDescription firstdate;

  public static final String SERIALIZED_NAME_FIRSTDATETAKEN = "firstdatetaken";
  @SerializedName(SERIALIZED_NAME_FIRSTDATETAKEN)
  private GroupDescription firstdatetaken;

  public static final String SERIALIZED_NAME_VIEWS = "views";
  @SerializedName(SERIALIZED_NAME_VIEWS)
  private GroupDescription views;

  public PersonPhotos() {
  }

  public PersonPhotos count(GroupDescription count) {
    
    
    
    
    this.count = count;
    return this;
  }

   /**
   * Get count
   * @return count
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public GroupDescription getCount() {
    return count;
  }


  public void setCount(GroupDescription count) {
    
    
    
    this.count = count;
  }


  public PersonPhotos firstdate(GroupDescription firstdate) {
    
    
    
    
    this.firstdate = firstdate;
    return this;
  }

   /**
   * Get firstdate
   * @return firstdate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public GroupDescription getFirstdate() {
    return firstdate;
  }


  public void setFirstdate(GroupDescription firstdate) {
    
    
    
    this.firstdate = firstdate;
  }


  public PersonPhotos firstdatetaken(GroupDescription firstdatetaken) {
    
    
    
    
    this.firstdatetaken = firstdatetaken;
    return this;
  }

   /**
   * Get firstdatetaken
   * @return firstdatetaken
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public GroupDescription getFirstdatetaken() {
    return firstdatetaken;
  }


  public void setFirstdatetaken(GroupDescription firstdatetaken) {
    
    
    
    this.firstdatetaken = firstdatetaken;
  }


  public PersonPhotos views(GroupDescription views) {
    
    
    
    
    this.views = views;
    return this;
  }

   /**
   * Get views
   * @return views
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public GroupDescription getViews() {
    return views;
  }


  public void setViews(GroupDescription views) {
    
    
    
    this.views = views;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the PersonPhotos instance itself
   */
  public PersonPhotos putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PersonPhotos personPhotos = (PersonPhotos) o;
    return Objects.equals(this.count, personPhotos.count) &&
        Objects.equals(this.firstdate, personPhotos.firstdate) &&
        Objects.equals(this.firstdatetaken, personPhotos.firstdatetaken) &&
        Objects.equals(this.views, personPhotos.views)&&
        Objects.equals(this.additionalProperties, personPhotos.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(count, firstdate, firstdatetaken, views, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PersonPhotos {\n");
    sb.append("    count: ").append(toIndentedString(count)).append("\n");
    sb.append("    firstdate: ").append(toIndentedString(firstdate)).append("\n");
    sb.append("    firstdatetaken: ").append(toIndentedString(firstdatetaken)).append("\n");
    sb.append("    views: ").append(toIndentedString(views)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("count");
    openapiFields.add("firstdate");
    openapiFields.add("firstdatetaken");
    openapiFields.add("views");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to PersonPhotos
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!PersonPhotos.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in PersonPhotos is not found in the empty JSON string", PersonPhotos.openapiRequiredFields.toString()));
        }
      }
      // validate the optional field `count`
      if (jsonObj.get("count") != null && !jsonObj.get("count").isJsonNull()) {
        GroupDescription.validateJsonObject(jsonObj.getAsJsonObject("count"));
      }
      // validate the optional field `firstdate`
      if (jsonObj.get("firstdate") != null && !jsonObj.get("firstdate").isJsonNull()) {
        GroupDescription.validateJsonObject(jsonObj.getAsJsonObject("firstdate"));
      }
      // validate the optional field `firstdatetaken`
      if (jsonObj.get("firstdatetaken") != null && !jsonObj.get("firstdatetaken").isJsonNull()) {
        GroupDescription.validateJsonObject(jsonObj.getAsJsonObject("firstdatetaken"));
      }
      // validate the optional field `views`
      if (jsonObj.get("views") != null && !jsonObj.get("views").isJsonNull()) {
        GroupDescription.validateJsonObject(jsonObj.getAsJsonObject("views"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!PersonPhotos.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'PersonPhotos' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<PersonPhotos> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(PersonPhotos.class));

       return (TypeAdapter<T>) new TypeAdapter<PersonPhotos>() {
           @Override
           public void write(JsonWriter out, PersonPhotos value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public PersonPhotos read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             PersonPhotos instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of PersonPhotos given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of PersonPhotos
  * @throws IOException if the JSON string is invalid with respect to PersonPhotos
  */
  public static PersonPhotos fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, PersonPhotos.class);
  }

 /**
  * Convert an instance of PersonPhotos to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

