/*
 * Flickr API Schema
 * A subset of Flickr's API defined in Swagger format.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * PhotoVisibility
 */@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class PhotoVisibility {
  public static final String SERIALIZED_NAME_ISFAMILY = "isfamily";
  @SerializedName(SERIALIZED_NAME_ISFAMILY)
  private Boolean isfamily;

  public static final String SERIALIZED_NAME_ISFRIEND = "isfriend";
  @SerializedName(SERIALIZED_NAME_ISFRIEND)
  private Boolean isfriend;

  public static final String SERIALIZED_NAME_ISPUBLIC = "ispublic";
  @SerializedName(SERIALIZED_NAME_ISPUBLIC)
  private Boolean ispublic;

  public PhotoVisibility() {
  }

  public PhotoVisibility isfamily(Boolean isfamily) {
    
    
    
    
    this.isfamily = isfamily;
    return this;
  }

   /**
   * Get isfamily
   * @return isfamily
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getIsfamily() {
    return isfamily;
  }


  public void setIsfamily(Boolean isfamily) {
    
    
    
    this.isfamily = isfamily;
  }


  public PhotoVisibility isfriend(Boolean isfriend) {
    
    
    
    
    this.isfriend = isfriend;
    return this;
  }

   /**
   * Get isfriend
   * @return isfriend
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getIsfriend() {
    return isfriend;
  }


  public void setIsfriend(Boolean isfriend) {
    
    
    
    this.isfriend = isfriend;
  }


  public PhotoVisibility ispublic(Boolean ispublic) {
    
    
    
    
    this.ispublic = ispublic;
    return this;
  }

   /**
   * Get ispublic
   * @return ispublic
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getIspublic() {
    return ispublic;
  }


  public void setIspublic(Boolean ispublic) {
    
    
    
    this.ispublic = ispublic;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the PhotoVisibility instance itself
   */
  public PhotoVisibility putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PhotoVisibility photoVisibility = (PhotoVisibility) o;
    return Objects.equals(this.isfamily, photoVisibility.isfamily) &&
        Objects.equals(this.isfriend, photoVisibility.isfriend) &&
        Objects.equals(this.ispublic, photoVisibility.ispublic)&&
        Objects.equals(this.additionalProperties, photoVisibility.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(isfamily, isfriend, ispublic, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PhotoVisibility {\n");
    sb.append("    isfamily: ").append(toIndentedString(isfamily)).append("\n");
    sb.append("    isfriend: ").append(toIndentedString(isfriend)).append("\n");
    sb.append("    ispublic: ").append(toIndentedString(ispublic)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("isfamily");
    openapiFields.add("isfriend");
    openapiFields.add("ispublic");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to PhotoVisibility
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!PhotoVisibility.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in PhotoVisibility is not found in the empty JSON string", PhotoVisibility.openapiRequiredFields.toString()));
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!PhotoVisibility.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'PhotoVisibility' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<PhotoVisibility> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(PhotoVisibility.class));

       return (TypeAdapter<T>) new TypeAdapter<PhotoVisibility>() {
           @Override
           public void write(JsonWriter out, PhotoVisibility value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public PhotoVisibility read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             PhotoVisibility instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of PhotoVisibility given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of PhotoVisibility
  * @throws IOException if the JSON string is invalid with respect to PhotoVisibility
  */
  public static PhotoVisibility fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, PhotoVisibility.class);
  }

 /**
  * Convert an instance of PhotoVisibility to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

