/*
 * Flickr API Schema
 * A subset of Flickr's API defined in Swagger format.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * PhotoDates
 */@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class PhotoDates {
  public static final String SERIALIZED_NAME_LASTUPDATE = "lastupdate";
  @SerializedName(SERIALIZED_NAME_LASTUPDATE)
  private String lastupdate;

  public static final String SERIALIZED_NAME_POSTED = "posted";
  @SerializedName(SERIALIZED_NAME_POSTED)
  private String posted;

  public static final String SERIALIZED_NAME_TAKEN = "taken";
  @SerializedName(SERIALIZED_NAME_TAKEN)
  private String taken;

  public static final String SERIALIZED_NAME_TAKENGRANULARITY = "takengranularity";
  @SerializedName(SERIALIZED_NAME_TAKENGRANULARITY)
  private String takengranularity;

  public static final String SERIALIZED_NAME_TAKENUNKNOWN = "takenunknown";
  @SerializedName(SERIALIZED_NAME_TAKENUNKNOWN)
  private Boolean takenunknown;

  public PhotoDates() {
  }

  public PhotoDates lastupdate(String lastupdate) {
    
    
    
    
    this.lastupdate = lastupdate;
    return this;
  }

   /**
   * Get lastupdate
   * @return lastupdate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getLastupdate() {
    return lastupdate;
  }


  public void setLastupdate(String lastupdate) {
    
    
    
    this.lastupdate = lastupdate;
  }


  public PhotoDates posted(String posted) {
    
    
    
    
    this.posted = posted;
    return this;
  }

   /**
   * Get posted
   * @return posted
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getPosted() {
    return posted;
  }


  public void setPosted(String posted) {
    
    
    
    this.posted = posted;
  }


  public PhotoDates taken(String taken) {
    
    
    
    
    this.taken = taken;
    return this;
  }

   /**
   * Get taken
   * @return taken
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getTaken() {
    return taken;
  }


  public void setTaken(String taken) {
    
    
    
    this.taken = taken;
  }


  public PhotoDates takengranularity(String takengranularity) {
    
    
    
    
    this.takengranularity = takengranularity;
    return this;
  }

   /**
   * Get takengranularity
   * @return takengranularity
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getTakengranularity() {
    return takengranularity;
  }


  public void setTakengranularity(String takengranularity) {
    
    
    
    this.takengranularity = takengranularity;
  }


  public PhotoDates takenunknown(Boolean takenunknown) {
    
    
    
    
    this.takenunknown = takenunknown;
    return this;
  }

   /**
   * Get takenunknown
   * @return takenunknown
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getTakenunknown() {
    return takenunknown;
  }


  public void setTakenunknown(Boolean takenunknown) {
    
    
    
    this.takenunknown = takenunknown;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the PhotoDates instance itself
   */
  public PhotoDates putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PhotoDates photoDates = (PhotoDates) o;
    return Objects.equals(this.lastupdate, photoDates.lastupdate) &&
        Objects.equals(this.posted, photoDates.posted) &&
        Objects.equals(this.taken, photoDates.taken) &&
        Objects.equals(this.takengranularity, photoDates.takengranularity) &&
        Objects.equals(this.takenunknown, photoDates.takenunknown)&&
        Objects.equals(this.additionalProperties, photoDates.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(lastupdate, posted, taken, takengranularity, takenunknown, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PhotoDates {\n");
    sb.append("    lastupdate: ").append(toIndentedString(lastupdate)).append("\n");
    sb.append("    posted: ").append(toIndentedString(posted)).append("\n");
    sb.append("    taken: ").append(toIndentedString(taken)).append("\n");
    sb.append("    takengranularity: ").append(toIndentedString(takengranularity)).append("\n");
    sb.append("    takenunknown: ").append(toIndentedString(takenunknown)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("lastupdate");
    openapiFields.add("posted");
    openapiFields.add("taken");
    openapiFields.add("takengranularity");
    openapiFields.add("takenunknown");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to PhotoDates
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!PhotoDates.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in PhotoDates is not found in the empty JSON string", PhotoDates.openapiRequiredFields.toString()));
        }
      }
      if ((jsonObj.get("lastupdate") != null && !jsonObj.get("lastupdate").isJsonNull()) && !jsonObj.get("lastupdate").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `lastupdate` to be a primitive type in the JSON string but got `%s`", jsonObj.get("lastupdate").toString()));
      }
      if ((jsonObj.get("posted") != null && !jsonObj.get("posted").isJsonNull()) && !jsonObj.get("posted").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `posted` to be a primitive type in the JSON string but got `%s`", jsonObj.get("posted").toString()));
      }
      if ((jsonObj.get("taken") != null && !jsonObj.get("taken").isJsonNull()) && !jsonObj.get("taken").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `taken` to be a primitive type in the JSON string but got `%s`", jsonObj.get("taken").toString()));
      }
      if ((jsonObj.get("takengranularity") != null && !jsonObj.get("takengranularity").isJsonNull()) && !jsonObj.get("takengranularity").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `takengranularity` to be a primitive type in the JSON string but got `%s`", jsonObj.get("takengranularity").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!PhotoDates.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'PhotoDates' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<PhotoDates> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(PhotoDates.class));

       return (TypeAdapter<T>) new TypeAdapter<PhotoDates>() {
           @Override
           public void write(JsonWriter out, PhotoDates value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public PhotoDates read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             PhotoDates instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of PhotoDates given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of PhotoDates
  * @throws IOException if the JSON string is invalid with respect to PhotoDates
  */
  public static PhotoDates fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, PhotoDates.class);
  }

 /**
  * Convert an instance of PhotoDates to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

