/*
 * Flickr API Schema
 * A subset of Flickr's API defined in Swagger format.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.Size;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * PublicGetPhotoSizesResponseSizes
 */@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class PublicGetPhotoSizesResponseSizes {
  public static final String SERIALIZED_NAME_CANBLOG = "canblog";
  @SerializedName(SERIALIZED_NAME_CANBLOG)
  private Double canblog;

  public static final String SERIALIZED_NAME_CANDOWNLOAD = "candownload";
  @SerializedName(SERIALIZED_NAME_CANDOWNLOAD)
  private Double candownload;

  public static final String SERIALIZED_NAME_CANPRINT = "canprint";
  @SerializedName(SERIALIZED_NAME_CANPRINT)
  private Double canprint;

  public static final String SERIALIZED_NAME_SIZES = "sizes";
  @SerializedName(SERIALIZED_NAME_SIZES)
  private List<Size> sizes = null;

  public PublicGetPhotoSizesResponseSizes() {
  }

  public PublicGetPhotoSizesResponseSizes canblog(Double canblog) {
    
    
    
    
    this.canblog = canblog;
    return this;
  }

  public PublicGetPhotoSizesResponseSizes canblog(Integer canblog) {
    
    
    
    
    this.canblog = canblog.doubleValue();
    return this;
  }

   /**
   * Get canblog
   * @return canblog
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Double getCanblog() {
    return canblog;
  }


  public void setCanblog(Double canblog) {
    
    
    
    this.canblog = canblog;
  }


  public PublicGetPhotoSizesResponseSizes candownload(Double candownload) {
    
    
    
    
    this.candownload = candownload;
    return this;
  }

  public PublicGetPhotoSizesResponseSizes candownload(Integer candownload) {
    
    
    
    
    this.candownload = candownload.doubleValue();
    return this;
  }

   /**
   * Get candownload
   * @return candownload
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Double getCandownload() {
    return candownload;
  }


  public void setCandownload(Double candownload) {
    
    
    
    this.candownload = candownload;
  }


  public PublicGetPhotoSizesResponseSizes canprint(Double canprint) {
    
    
    
    
    this.canprint = canprint;
    return this;
  }

  public PublicGetPhotoSizesResponseSizes canprint(Integer canprint) {
    
    
    
    
    this.canprint = canprint.doubleValue();
    return this;
  }

   /**
   * Get canprint
   * @return canprint
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Double getCanprint() {
    return canprint;
  }


  public void setCanprint(Double canprint) {
    
    
    
    this.canprint = canprint;
  }


  public PublicGetPhotoSizesResponseSizes sizes(List<Size> sizes) {
    
    
    
    
    this.sizes = sizes;
    return this;
  }

  public PublicGetPhotoSizesResponseSizes addSizesItem(Size sizesItem) {
    if (this.sizes == null) {
      this.sizes = new ArrayList<>();
    }
    this.sizes.add(sizesItem);
    return this;
  }

   /**
   * Get sizes
   * @return sizes
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<Size> getSizes() {
    return sizes;
  }


  public void setSizes(List<Size> sizes) {
    
    
    
    this.sizes = sizes;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the PublicGetPhotoSizesResponseSizes instance itself
   */
  public PublicGetPhotoSizesResponseSizes putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PublicGetPhotoSizesResponseSizes publicGetPhotoSizesResponseSizes = (PublicGetPhotoSizesResponseSizes) o;
    return Objects.equals(this.canblog, publicGetPhotoSizesResponseSizes.canblog) &&
        Objects.equals(this.candownload, publicGetPhotoSizesResponseSizes.candownload) &&
        Objects.equals(this.canprint, publicGetPhotoSizesResponseSizes.canprint) &&
        Objects.equals(this.sizes, publicGetPhotoSizesResponseSizes.sizes)&&
        Objects.equals(this.additionalProperties, publicGetPhotoSizesResponseSizes.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(canblog, candownload, canprint, sizes, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PublicGetPhotoSizesResponseSizes {\n");
    sb.append("    canblog: ").append(toIndentedString(canblog)).append("\n");
    sb.append("    candownload: ").append(toIndentedString(candownload)).append("\n");
    sb.append("    canprint: ").append(toIndentedString(canprint)).append("\n");
    sb.append("    sizes: ").append(toIndentedString(sizes)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("canblog");
    openapiFields.add("candownload");
    openapiFields.add("canprint");
    openapiFields.add("sizes");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to PublicGetPhotoSizesResponseSizes
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!PublicGetPhotoSizesResponseSizes.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in PublicGetPhotoSizesResponseSizes is not found in the empty JSON string", PublicGetPhotoSizesResponseSizes.openapiRequiredFields.toString()));
        }
      }
      if (jsonObj.get("sizes") != null && !jsonObj.get("sizes").isJsonNull()) {
        JsonArray jsonArraysizes = jsonObj.getAsJsonArray("sizes");
        if (jsonArraysizes != null) {
          // ensure the json data is an array
          if (!jsonObj.get("sizes").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `sizes` to be an array in the JSON string but got `%s`", jsonObj.get("sizes").toString()));
          }

          // validate the optional field `sizes` (array)
          for (int i = 0; i < jsonArraysizes.size(); i++) {
            Size.validateJsonObject(jsonArraysizes.get(i).getAsJsonObject());
          };
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!PublicGetPhotoSizesResponseSizes.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'PublicGetPhotoSizesResponseSizes' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<PublicGetPhotoSizesResponseSizes> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(PublicGetPhotoSizesResponseSizes.class));

       return (TypeAdapter<T>) new TypeAdapter<PublicGetPhotoSizesResponseSizes>() {
           @Override
           public void write(JsonWriter out, PublicGetPhotoSizesResponseSizes value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public PublicGetPhotoSizesResponseSizes read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             PublicGetPhotoSizesResponseSizes instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of PublicGetPhotoSizesResponseSizes given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of PublicGetPhotoSizesResponseSizes
  * @throws IOException if the JSON string is invalid with respect to PublicGetPhotoSizesResponseSizes
  */
  public static PublicGetPhotoSizesResponseSizes fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, PublicGetPhotoSizesResponseSizes.class);
  }

 /**
  * Convert an instance of PublicGetPhotoSizesResponseSizes to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

