/*
 * Flickr API Schema
 * A subset of Flickr's API defined in Swagger format.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.GroupDescription;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * PublicGetPhotoExifResponsePhotoExifInner
 */@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class PublicGetPhotoExifResponsePhotoExifInner {
  public static final String SERIALIZED_NAME_LABEL = "label";
  @SerializedName(SERIALIZED_NAME_LABEL)
  private String label;

  public static final String SERIALIZED_NAME_RAW = "raw";
  @SerializedName(SERIALIZED_NAME_RAW)
  private GroupDescription raw;

  public static final String SERIALIZED_NAME_TAG = "tag";
  @SerializedName(SERIALIZED_NAME_TAG)
  private String tag;

  public static final String SERIALIZED_NAME_TAGSPACE = "tagspace";
  @SerializedName(SERIALIZED_NAME_TAGSPACE)
  private String tagspace;

  public static final String SERIALIZED_NAME_TAGSPACEID = "tagspaceid";
  @SerializedName(SERIALIZED_NAME_TAGSPACEID)
  private String tagspaceid;

  public PublicGetPhotoExifResponsePhotoExifInner() {
  }

  public PublicGetPhotoExifResponsePhotoExifInner label(String label) {
    
    
    
    
    this.label = label;
    return this;
  }

   /**
   * Get label
   * @return label
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getLabel() {
    return label;
  }


  public void setLabel(String label) {
    
    
    
    this.label = label;
  }


  public PublicGetPhotoExifResponsePhotoExifInner raw(GroupDescription raw) {
    
    
    
    
    this.raw = raw;
    return this;
  }

   /**
   * Get raw
   * @return raw
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public GroupDescription getRaw() {
    return raw;
  }


  public void setRaw(GroupDescription raw) {
    
    
    
    this.raw = raw;
  }


  public PublicGetPhotoExifResponsePhotoExifInner tag(String tag) {
    
    
    
    
    this.tag = tag;
    return this;
  }

   /**
   * Get tag
   * @return tag
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getTag() {
    return tag;
  }


  public void setTag(String tag) {
    
    
    
    this.tag = tag;
  }


  public PublicGetPhotoExifResponsePhotoExifInner tagspace(String tagspace) {
    
    
    
    
    this.tagspace = tagspace;
    return this;
  }

   /**
   * Get tagspace
   * @return tagspace
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getTagspace() {
    return tagspace;
  }


  public void setTagspace(String tagspace) {
    
    
    
    this.tagspace = tagspace;
  }


  public PublicGetPhotoExifResponsePhotoExifInner tagspaceid(String tagspaceid) {
    
    
    
    
    this.tagspaceid = tagspaceid;
    return this;
  }

   /**
   * Get tagspaceid
   * @return tagspaceid
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getTagspaceid() {
    return tagspaceid;
  }


  public void setTagspaceid(String tagspaceid) {
    
    
    
    this.tagspaceid = tagspaceid;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the PublicGetPhotoExifResponsePhotoExifInner instance itself
   */
  public PublicGetPhotoExifResponsePhotoExifInner putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PublicGetPhotoExifResponsePhotoExifInner publicGetPhotoExifResponsePhotoExifInner = (PublicGetPhotoExifResponsePhotoExifInner) o;
    return Objects.equals(this.label, publicGetPhotoExifResponsePhotoExifInner.label) &&
        Objects.equals(this.raw, publicGetPhotoExifResponsePhotoExifInner.raw) &&
        Objects.equals(this.tag, publicGetPhotoExifResponsePhotoExifInner.tag) &&
        Objects.equals(this.tagspace, publicGetPhotoExifResponsePhotoExifInner.tagspace) &&
        Objects.equals(this.tagspaceid, publicGetPhotoExifResponsePhotoExifInner.tagspaceid)&&
        Objects.equals(this.additionalProperties, publicGetPhotoExifResponsePhotoExifInner.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(label, raw, tag, tagspace, tagspaceid, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PublicGetPhotoExifResponsePhotoExifInner {\n");
    sb.append("    label: ").append(toIndentedString(label)).append("\n");
    sb.append("    raw: ").append(toIndentedString(raw)).append("\n");
    sb.append("    tag: ").append(toIndentedString(tag)).append("\n");
    sb.append("    tagspace: ").append(toIndentedString(tagspace)).append("\n");
    sb.append("    tagspaceid: ").append(toIndentedString(tagspaceid)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("label");
    openapiFields.add("raw");
    openapiFields.add("tag");
    openapiFields.add("tagspace");
    openapiFields.add("tagspaceid");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to PublicGetPhotoExifResponsePhotoExifInner
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!PublicGetPhotoExifResponsePhotoExifInner.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in PublicGetPhotoExifResponsePhotoExifInner is not found in the empty JSON string", PublicGetPhotoExifResponsePhotoExifInner.openapiRequiredFields.toString()));
        }
      }
      if ((jsonObj.get("label") != null && !jsonObj.get("label").isJsonNull()) && !jsonObj.get("label").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `label` to be a primitive type in the JSON string but got `%s`", jsonObj.get("label").toString()));
      }
      // validate the optional field `raw`
      if (jsonObj.get("raw") != null && !jsonObj.get("raw").isJsonNull()) {
        GroupDescription.validateJsonObject(jsonObj.getAsJsonObject("raw"));
      }
      if ((jsonObj.get("tag") != null && !jsonObj.get("tag").isJsonNull()) && !jsonObj.get("tag").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `tag` to be a primitive type in the JSON string but got `%s`", jsonObj.get("tag").toString()));
      }
      if ((jsonObj.get("tagspace") != null && !jsonObj.get("tagspace").isJsonNull()) && !jsonObj.get("tagspace").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `tagspace` to be a primitive type in the JSON string but got `%s`", jsonObj.get("tagspace").toString()));
      }
      if ((jsonObj.get("tagspaceid") != null && !jsonObj.get("tagspaceid").isJsonNull()) && !jsonObj.get("tagspaceid").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `tagspaceid` to be a primitive type in the JSON string but got `%s`", jsonObj.get("tagspaceid").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!PublicGetPhotoExifResponsePhotoExifInner.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'PublicGetPhotoExifResponsePhotoExifInner' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<PublicGetPhotoExifResponsePhotoExifInner> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(PublicGetPhotoExifResponsePhotoExifInner.class));

       return (TypeAdapter<T>) new TypeAdapter<PublicGetPhotoExifResponsePhotoExifInner>() {
           @Override
           public void write(JsonWriter out, PublicGetPhotoExifResponsePhotoExifInner value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public PublicGetPhotoExifResponsePhotoExifInner read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             PublicGetPhotoExifResponsePhotoExifInner instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of PublicGetPhotoExifResponsePhotoExifInner given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of PublicGetPhotoExifResponsePhotoExifInner
  * @throws IOException if the JSON string is invalid with respect to PublicGetPhotoExifResponsePhotoExifInner
  */
  public static PublicGetPhotoExifResponsePhotoExifInner fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, PublicGetPhotoExifResponsePhotoExifInner.class);
  }

 /**
  * Convert an instance of PublicGetPhotoExifResponsePhotoExifInner to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

