/*
 * Flickr API Schema
 * A subset of Flickr's API defined in Swagger format.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.PublicGetPhotoExifResponsePhotoExifInner;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * PublicGetPhotoExifResponsePhoto
 */@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class PublicGetPhotoExifResponsePhoto {
  public static final String SERIALIZED_NAME_CAMERA = "camera";
  @SerializedName(SERIALIZED_NAME_CAMERA)
  private String camera;

  public static final String SERIALIZED_NAME_EXIF = "exif";
  @SerializedName(SERIALIZED_NAME_EXIF)
  private List<PublicGetPhotoExifResponsePhotoExifInner> exif = null;

  public static final String SERIALIZED_NAME_FARM = "farm";
  @SerializedName(SERIALIZED_NAME_FARM)
  private String farm;

  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private String id;

  public static final String SERIALIZED_NAME_SECRET = "secret";
  @SerializedName(SERIALIZED_NAME_SECRET)
  private String secret;

  public static final String SERIALIZED_NAME_SERVER = "server";
  @SerializedName(SERIALIZED_NAME_SERVER)
  private String server;

  public PublicGetPhotoExifResponsePhoto() {
  }

  public PublicGetPhotoExifResponsePhoto camera(String camera) {
    
    
    
    
    this.camera = camera;
    return this;
  }

   /**
   * Get camera
   * @return camera
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getCamera() {
    return camera;
  }


  public void setCamera(String camera) {
    
    
    
    this.camera = camera;
  }


  public PublicGetPhotoExifResponsePhoto exif(List<PublicGetPhotoExifResponsePhotoExifInner> exif) {
    
    
    
    
    this.exif = exif;
    return this;
  }

  public PublicGetPhotoExifResponsePhoto addExifItem(PublicGetPhotoExifResponsePhotoExifInner exifItem) {
    if (this.exif == null) {
      this.exif = new ArrayList<>();
    }
    this.exif.add(exifItem);
    return this;
  }

   /**
   * Get exif
   * @return exif
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<PublicGetPhotoExifResponsePhotoExifInner> getExif() {
    return exif;
  }


  public void setExif(List<PublicGetPhotoExifResponsePhotoExifInner> exif) {
    
    
    
    this.exif = exif;
  }


  public PublicGetPhotoExifResponsePhoto farm(String farm) {
    
    
    
    
    this.farm = farm;
    return this;
  }

   /**
   * Get farm
   * @return farm
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getFarm() {
    return farm;
  }


  public void setFarm(String farm) {
    
    
    
    this.farm = farm;
  }


  public PublicGetPhotoExifResponsePhoto id(String id) {
    
    
    
    
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getId() {
    return id;
  }


  public void setId(String id) {
    
    
    
    this.id = id;
  }


  public PublicGetPhotoExifResponsePhoto secret(String secret) {
    
    
    
    
    this.secret = secret;
    return this;
  }

   /**
   * Get secret
   * @return secret
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getSecret() {
    return secret;
  }


  public void setSecret(String secret) {
    
    
    
    this.secret = secret;
  }


  public PublicGetPhotoExifResponsePhoto server(String server) {
    
    
    
    
    this.server = server;
    return this;
  }

   /**
   * Get server
   * @return server
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getServer() {
    return server;
  }


  public void setServer(String server) {
    
    
    
    this.server = server;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the PublicGetPhotoExifResponsePhoto instance itself
   */
  public PublicGetPhotoExifResponsePhoto putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PublicGetPhotoExifResponsePhoto publicGetPhotoExifResponsePhoto = (PublicGetPhotoExifResponsePhoto) o;
    return Objects.equals(this.camera, publicGetPhotoExifResponsePhoto.camera) &&
        Objects.equals(this.exif, publicGetPhotoExifResponsePhoto.exif) &&
        Objects.equals(this.farm, publicGetPhotoExifResponsePhoto.farm) &&
        Objects.equals(this.id, publicGetPhotoExifResponsePhoto.id) &&
        Objects.equals(this.secret, publicGetPhotoExifResponsePhoto.secret) &&
        Objects.equals(this.server, publicGetPhotoExifResponsePhoto.server)&&
        Objects.equals(this.additionalProperties, publicGetPhotoExifResponsePhoto.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(camera, exif, farm, id, secret, server, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PublicGetPhotoExifResponsePhoto {\n");
    sb.append("    camera: ").append(toIndentedString(camera)).append("\n");
    sb.append("    exif: ").append(toIndentedString(exif)).append("\n");
    sb.append("    farm: ").append(toIndentedString(farm)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    secret: ").append(toIndentedString(secret)).append("\n");
    sb.append("    server: ").append(toIndentedString(server)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("camera");
    openapiFields.add("exif");
    openapiFields.add("farm");
    openapiFields.add("id");
    openapiFields.add("secret");
    openapiFields.add("server");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to PublicGetPhotoExifResponsePhoto
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!PublicGetPhotoExifResponsePhoto.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in PublicGetPhotoExifResponsePhoto is not found in the empty JSON string", PublicGetPhotoExifResponsePhoto.openapiRequiredFields.toString()));
        }
      }
      if ((jsonObj.get("camera") != null && !jsonObj.get("camera").isJsonNull()) && !jsonObj.get("camera").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `camera` to be a primitive type in the JSON string but got `%s`", jsonObj.get("camera").toString()));
      }
      if (jsonObj.get("exif") != null && !jsonObj.get("exif").isJsonNull()) {
        JsonArray jsonArrayexif = jsonObj.getAsJsonArray("exif");
        if (jsonArrayexif != null) {
          // ensure the json data is an array
          if (!jsonObj.get("exif").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `exif` to be an array in the JSON string but got `%s`", jsonObj.get("exif").toString()));
          }

          // validate the optional field `exif` (array)
          for (int i = 0; i < jsonArrayexif.size(); i++) {
            PublicGetPhotoExifResponsePhotoExifInner.validateJsonObject(jsonArrayexif.get(i).getAsJsonObject());
          };
        }
      }
      if ((jsonObj.get("farm") != null && !jsonObj.get("farm").isJsonNull()) && !jsonObj.get("farm").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `farm` to be a primitive type in the JSON string but got `%s`", jsonObj.get("farm").toString()));
      }
      if ((jsonObj.get("id") != null && !jsonObj.get("id").isJsonNull()) && !jsonObj.get("id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("id").toString()));
      }
      if ((jsonObj.get("secret") != null && !jsonObj.get("secret").isJsonNull()) && !jsonObj.get("secret").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `secret` to be a primitive type in the JSON string but got `%s`", jsonObj.get("secret").toString()));
      }
      if ((jsonObj.get("server") != null && !jsonObj.get("server").isJsonNull()) && !jsonObj.get("server").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `server` to be a primitive type in the JSON string but got `%s`", jsonObj.get("server").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!PublicGetPhotoExifResponsePhoto.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'PublicGetPhotoExifResponsePhoto' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<PublicGetPhotoExifResponsePhoto> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(PublicGetPhotoExifResponsePhoto.class));

       return (TypeAdapter<T>) new TypeAdapter<PublicGetPhotoExifResponsePhoto>() {
           @Override
           public void write(JsonWriter out, PublicGetPhotoExifResponsePhoto value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public PublicGetPhotoExifResponsePhoto read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             PublicGetPhotoExifResponsePhoto instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of PublicGetPhotoExifResponsePhoto given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of PublicGetPhotoExifResponsePhoto
  * @throws IOException if the JSON string is invalid with respect to PublicGetPhotoExifResponsePhoto
  */
  public static PublicGetPhotoExifResponsePhoto fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, PublicGetPhotoExifResponsePhoto.class);
  }

 /**
  * Convert an instance of PublicGetPhotoExifResponsePhoto to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

